version: 0.0
os: linux
files:
 - source: .
   destination: /var/www/cheese_namam
permissions:
  - object: /var/www/cheese_namam/test.sh
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 777
hooks:
  AfterInstall:
   - location: /var/www/cheese_namam/test.sh
     timeout: 300
     runas: ubuntu
